version: "3"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: curso
      POSTGRES_PASSWORD: curso
      POSTGRES_DB: curso
    ports:
      - 5432:5432
  curso:
    depends_on: [db]
    build: .
    volumes:
      - .:/usr/app
    ports:
      - 3333:3333
